version: '3'

services:
  install-dependencies:
    image: node:16.15.0-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm install

  build:
    image: node:16.15.0-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm run build
    environment:
      REACT_APP_CI_ENV: 1
    env_file:
      - ./gravity.env
    depends_on:
      install-dependencies:
        condition: service_completed_successfully

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate-db:
    image: node:16.15.0-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm run server:db:migrate
    environment:
      DATABASE_URL: postgresql://postgres@postgres/planka
    depends_on:
      postgres:
        condition: service_healthy
      build:
        condition: service_completed_successfully

  # Note: this might fail at second startup...
  seed-db:
    image: node:16.15.0-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm run server:db:seed
    environment:
      DATABASE_URL: postgresql://postgres@postgres/planka
    depends_on:
      migrate-db:
        condition: service_completed_successfully

  planka:
    image: node:16.15.0-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm run start:ci
    environment:
      PORT: 3000
      BASE_URL: http://localhost:3000
      NO_SSL: 1
      DATABASE_URL: postgresql://postgres@postgres/planka
      SECRET_KEY: notsecretkey
    env_file:
      - ./gravity.env
    ports:
      - 3000:3000
    depends_on:
      migrate-db:
        condition: service_completed_successfully

volumes:
  db-data:
