version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-d", "planka", "-U", "Postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  db-data:
