describe('Board management', () => {
  beforeEach(() => {
    cy.task('db:reset');
  });

  // it("creates a project, a board two lists and a card", () => {
  //   cy.log("Session started")
  //   cy.viewport(1440, 796)
  //   cy.visit("/login")
  //   cy.log("Step 1: change")
  //   cy.get(":nth-child(1) > .ui > input").type("{selectall}").type("demo@demo.demo")
  //   cy.log("Step 2: change")
  //   cy.get(":nth-child(2) > .ui > input").type("{selectall}").type("demo")
  //   cy.log("Step 3: click")
  //   cy.get(".field > .ui").click()
  //   cy.log("Step 4: click")
  //   cy.get(".Projects_addGridIcon__RqH-D").click()
  //   cy.log("Step 5: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 6: change")
  //   cy.get("input").type("{selectall}").type("My project")
  //   cy.log("Step 7: click")
  //   cy.get(".green").click()
  //   cy.log("Step 8: click")
  //   cy.get(".plus").click()
  //   cy.log("Step 9: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 10: change")
  //   cy.get("input").type("{selectall}").type("My board")
  //   cy.log("Step 11: click")
  //   cy.get(".positive").click()
  //   cy.log("Step 12: click")
  //   cy.get(".Board_addListButtonText__o-FjU").click()
  //   cy.log("Step 13: change")
  //   cy.get("input").type("{selectall}").type("My List")
  //   cy.log("Step 14: click")
  //   cy.get(".ListAdd_controls__A5EmO > .ui").click()
  //   cy.log("Step 15: change")
  //   cy.get("input").type("{selectall}").type("My second list")
  //   cy.log("Step 16: click")
  //   cy.get(".ListAdd_controls__A5EmO > .ui").click()
  //   cy.log("Step 23: click")
  //   cy.get(":nth-child(1) > .List_outerWrapper__B4Idr > .List_addCardButton__8vjKW > .List_addCardButtonText__q66qy").click()
  //   cy.log("Step 24: keydown")
  //   cy.focused().type("{selectall}").type("My card")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 25: click")
  //   cy.get(".right > :nth-child(3)").click()
  //   cy.log("Step 26: click")
  //   cy.get(".content > .ui > :nth-child(2)").click()
  // })

  // it("c06c8390-5553-474a-876e-f539b73844e0", () => {
  //   cy.log("Session started")
  //   cy.viewport(1440, 796)
  //   cy.visit("/login")
  //   cy.log("Step 1: change")
  //   cy.get(":nth-child(1) > .ui > input").type("{selectall}").type("demo@demo.demo")
  //   cy.log("Step 2: change")
  //   cy.get(":nth-child(2) > .ui > input").type("{selectall}").type("demo")
  //   cy.log("Step 3: click")
  //   cy.get(".field > .ui").click()
  //   cy.log("Step 4: click")
  //   cy.get("path").click()
  //   cy.log("Step 5: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 6: change")
  //   cy.get("input").type("{selectall}").type("mon projet")
  //   cy.log("Step 7: click")
  //   cy.get(".green").click()
  //   cy.log("Step 8: click")
  //   cy.get(".plus").click()
  //   cy.log("Step 9: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 10: change")
  //   cy.get("input").type("{selectall}").type("mon board")
  //   cy.log("Step 11: click")
  //   cy.get(".positive").click()
  //   cy.log("Step 12: click")
  //   cy.get(".Board_addListButtonText__o-FjU").click()
  //   cy.log("Step 13: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 14: click")
  //   cy.get(".ListAdd_controls__A5EmO > .ui").click()
  //   cy.log("Step 15: change")
  //   cy.get("input").type("{selectall}").type("to do")
  //   cy.log("Step 16: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 17: change")
  //   cy.get("input").type("{selectall}").type("in progress")
  //   cy.log("Step 18: click")
  //   cy.get(".ListAdd_controls__A5EmO > .ui").click()
  //   cy.log("Step 19: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 20: change")
  //   cy.get("input").type("{selectall}").type("done")
  //   cy.log("Step 21: click")
  //   cy.get(".ListAdd_controls__A5EmO > .ui").click()
  //   cy.log("Step 22: click")
  //   cy.get(":nth-child(1) > .List_outerWrapper__B4Idr > .List_addCardButton__8vjKW > .List_addCardButtonText__q66qy").click()
  //   cy.log("Step 23: click")
  //   cy.get(":nth-child(1) > .List_outerWrapper__B4Idr > .List_cardsInnerWrapper__t3Hsf > :nth-child(1) > :nth-child(1) > .List_cards__soDK7 > .form > :nth-child(2) > .ui").click()
  //   cy.log("Step 24: click")
  //   cy.get(":nth-child(1) > .List_outerWrapper__B4Idr > .List_cardsInnerWrapper__t3Hsf > :nth-child(1) > :nth-child(1) > .List_cards__soDK7 > .form > .CardAdd_fieldWrapper__zxVml > textarea").click()
  //   cy.log("Step 25: keydown")
  //   cy.focused().type("{Enter}")
  //   cy.log("Step 26: click")
  //   cy.get(".right > :nth-child(3)").click()
  //   cy.log("Step 27: click")
  //   cy.get(".content > .ui > :nth-child(2)").click()
  // })
})
